Attempt to reduce test failures due to requesting from external service - Intermittent error controller_test.go:832: error sending proxied HTTP request: Get https://raw.githubusercontent.com/Psiphon-Labs/psiphon-tunnel-core/master/LICENSE: unexpected EOF - Try explicitly closing persistent connections and adding a short delay between back-to-back requests - Eventually, we should mock the upstream web server and not use and external service